language: ruby
rvm:
- 2.3.3

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
# url-ignore ignores #left to avoid common errors like:
# linking to internal hash #fn:1 that does not exist

install: gem install jekyll html-proofer jekyll-redirect-from
script: jekyll build && htmlproofer ./_site --url-ignore "/#.*/" --alt-ignore '/.*/'

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
